[tool.poetry]
name = "lightrdf"
version = "0.2.0"
description = "A fast and lightweight Python RDF parser which wraps bindings to Rust's Rio using PyO3"
authors = ["Kentaro Ozeki <kentaro.ozeki+dev@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
tox = "^3.20.1"
maturin = "^0.8.3"
tox-gh-actions = "^2.1.0"

[build-system]
requires = ["maturin"]
build-backend = "maturin"
